// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf0oIkpXSZjduPqM7YNce1Gkgy6Wt1XDQ',
    appId: '1:454008920444:web:d59574d3e9917c18aaacf9',
    messagingSenderId: '454008920444',
    projectId: 'chatyy-251e8',
    authDomain: 'chatyy-251e8.firebaseapp.com',
    storageBucket: 'chatyy-251e8.appspot.com',
    measurementId: 'G-J4551F7MSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR5nxkErnMaM5qZMrtq2DtI8UY2z-rXaU',
    appId: '1:454008920444:android:63bbddaffda18d42aaacf9',
    messagingSenderId: '454008920444',
    projectId: 'chatyy-251e8',
    storageBucket: 'chatyy-251e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsdY1sZjtCluaPwgp7T28-YytZTW56-lU',
    appId: '1:454008920444:ios:eafe827c1d2e3bbeaaacf9',
    messagingSenderId: '454008920444',
    projectId: 'chatyy-251e8',
    storageBucket: 'chatyy-251e8.appspot.com',
    iosClientId: '454008920444-gnp752rta54298p373q8ucik07aht4im.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatyy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsdY1sZjtCluaPwgp7T28-YytZTW56-lU',
    appId: '1:454008920444:ios:f3059212e4506832aaacf9',
    messagingSenderId: '454008920444',
    projectId: 'chatyy-251e8',
    storageBucket: 'chatyy-251e8.appspot.com',
    iosClientId: '454008920444-7uv221mnra95fqvs1ojsihhn1u4t819q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatyy.RunnerTests',
  );
}
